-- Supabase SQL for Unbl0cked Zone community chat/posts.
-- Run this in Supabase Dashboard > SQL Editor, then enable Realtime for chat_messages and posts.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Member',
  role text not null default 'member' check (role in ('owner','admin','mod','member','banned')),
  created_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) <= 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) <= 120),
  body text not null check (char_length(body) <= 4000),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.chat_messages enable row level security;
alter table public.posts enable row level security;

create policy "profiles are readable" on public.profiles for select using (true);
create policy "users create own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "users update own display name" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id and role = (select role from public.profiles where id = auth.uid()));

create policy "chat readable" on public.chat_messages for select using (true);
create policy "members can chat" on public.chat_messages for insert with check (
  auth.uid() = user_id and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin','mod','member'))
);

create policy "posts readable" on public.posts for select using (true);
create policy "staff can post" on public.posts for insert with check (
  auth.uid() = user_id and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin','mod'))
);

alter publication supabase_realtime add table public.chat_messages;
alter publication supabase_realtime add table public.posts;

-- After your account exists, make yourself owner by replacing the email:
-- update public.profiles set role = 'owner' where id = (select id from auth.users where email = 'YOUR_EMAIL@example.com');