-- Supabase SQL for Unbl0cked Zone community chat/posts with safe OAuth identity.
-- Run in Supabase Dashboard > SQL Editor. Enable Google/Microsoft OAuth in Authentication > Providers.
-- The browser never sets email or role. Supabase derives them from the authenticated OAuth token.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text not null default 'Member' check (char_length(display_name) between 2 and 24),
  role text not null default 'member' check (role in ('owner','admin','mod','member','banned')),
  created_at timestamptz not null default now()
);

create or replace function public.set_profile_identity()
returns trigger
language plpgsql
security definer
as $$
declare
  jwt_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
begin
  new.email := jwt_email;
  if jwt_email = lower('GoldsteinI.166@student.cbsd.org') then
    new.role := 'owner';
  elsif tg_op = 'INSERT' then
    new.role := 'member';
  else
    new.role := old.role;
  end if;
  return new;
end;
$$;

drop trigger if exists set_profile_identity_trigger on public.profiles;
create trigger set_profile_identity_trigger
before insert or update on public.profiles
for each row execute function public.set_profile_identity();

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  body text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.chat_messages enable row level security;
alter table public.posts enable row level security;

drop policy if exists "profiles readable" on public.profiles;
drop policy if exists "users insert own profile" on public.profiles;
drop policy if exists "users update own display name" on public.profiles;
drop policy if exists "chat readable" on public.chat_messages;
drop policy if exists "signed in users can chat" on public.chat_messages;
drop policy if exists "posts readable" on public.posts;
drop policy if exists "owners can post" on public.posts;

create policy "profiles readable" on public.profiles for select using (true);
create policy "users insert own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "users update own display name" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "chat readable" on public.chat_messages for select using (true);
create policy "signed in users can chat" on public.chat_messages for insert with check (
  auth.uid() = user_id and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin','mod','member'))
);

create policy "posts readable" on public.posts for select using (true);
create policy "owners can post" on public.posts for insert with check (
  auth.uid() = user_id and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'owner')
);

do $$ begin
  alter publication supabase_realtime add table public.chat_messages;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter publication supabase_realtime add table public.posts;
exception when duplicate_object then null;
end $$;